### ISSUE TITLE
Test case "InstantiationWithDuplicatedSubscribers" error

### ISSUE THREAD

**Issue by VivienCPNV** [NicolasGlassey/GPR1-SocialNetwork#3]
Le test "test_constructor_InstantiationWithDuplicatedSubscribers_ThrowsException" n'instancie pas la classe "Twitter" avec un liste contenant des copie du même "Subsriber".

```php
$expectedAmountOfSubscriber = 15;
$followers = $this->generateObservers($expectedAmountOfSubscriber);
//Une liste de 15 followers est créée
//["Follower 1", "Follower 2", "Follower 3", "Follower 4", "Follower 5", ....]
$followersWithDuplicate = array();
//Une liste vide est créée
//[]
//Le follower 1 est rajouter à cette liste
array_push($followersWithDuplicate, $followers[0]);
//Une liste avec l'objet follower 1 est créée mais celle-ci ne contient pas plusieurs copies du même objet.
//["Follower 1"]
```

Corrigé possible:
```php
$expectedAmountOfSubscriber = 15;
$followers = $this->generateObservers($expectedAmountOfSubscriber);
array_push($followers, $followers[0]);
```
Est-ce que j'ai juste pas compris ce que doit faire le test ?

**Comment by NicolasGlassey** [comment]
@VivienCPNV 

Bonjour Vivien,

Vous avez tout à fait bien lu, compris et corrigé cette méthode de test.

Ce message pour vous confirmer que j'ai bien vu votre issue et que je la valoriserai dans votre examen de GPR1.

Bonne suite de week-end !
